package com.myspace.patient;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.math.BigDecimal freeAmount;
	private int age;

	private java.lang.Boolean isElligible;

	private java.lang.Boolean firstUser;

	private java.lang.Boolean isInsured;

	private String insuranceCompany;

	private java.math.BigDecimal billAmt;

	public Patient() {
	}

	public java.math.BigDecimal getFreeAmount() {
		return this.freeAmount;
	}

	public void setFreeAmount(java.math.BigDecimal freeAmount) {
		this.freeAmount = freeAmount;
	}

	public java.lang.Boolean getIsElligible() {
		return this.isElligible;
	}

	public void setIsElligible(java.lang.Boolean isElligible) {
		this.isElligible = isElligible;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.lang.Boolean getFirstUser() {
		return this.firstUser;
	}

	public void setFirstUser(java.lang.Boolean firstUser) {
		this.firstUser = firstUser;
	}

	public java.lang.Boolean getIsInsured() {
		return this.isInsured;
	}

	public void setIsInsured(java.lang.Boolean isInsured) {
		this.isInsured = isInsured;
	}

	public java.lang.String getInsuranceCompany() {
		return this.insuranceCompany;
	}

	public void setInsuranceCompany(java.lang.String insuranceCompany) {
		this.insuranceCompany = insuranceCompany;
	}

	public java.math.BigDecimal getBillAmt() {
		return this.billAmt;
	}

	public void setBillAmt(java.math.BigDecimal billAmt) {
		this.billAmt = billAmt;
	}

	public Patient(java.math.BigDecimal freeAmount, int age,
			java.lang.Boolean isElligible, java.lang.Boolean firstUser,
			java.lang.Boolean isInsured, java.lang.String insuranceCompany,
			java.math.BigDecimal billAmt) {
		this.freeAmount = freeAmount;
		this.age = age;
		this.isElligible = isElligible;
		this.firstUser = firstUser;
		this.isInsured = isInsured;
		this.insuranceCompany = insuranceCompany;
		this.billAmt = billAmt;
	}

}